### ISSUE TITLE
2_oct_issue 1

### ISSUE THREAD

**Issue by Suman-Banakar** [Suman-Banakar/Funder1-repo-2-oct#1]
Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Curabitur aliquet quam id dui posuere blandit. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur aliquet quam id dui posuere blandit.
Nulla quis lorem ut libero malesuada feugiat. Nulla quis lorem ut libero malesuada feugiat. Donec rutrum congue leo eget malesuada. Donec sollicitudin molestie malesuada. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur aliquet quam id dui posuere blandit. Cras ultricies ligula sed magna dictum porta. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Curabitur aliquet quam id dui posuere blandit. Pellentesque in ipsum id orci porta dapibus.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done**

<hr>

**The following Contributors have applied to start work .**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a> has been approved to work.**

**Message:** I want to work on this


**2) <a href='https://sandbox.app.gitcommits.com/profile/SapneshNaik'>SapneshNaik</a> has applied to start work. (Funders only: <a href='https://sandbox.app.gitcommits.com/issue/funder-1-issue-1?action=approve&worker=SapneshNaik'>Approve</a> | <a href='https://sandbox.app.gitcommits.com/issue/funder-1-issue-1?action=reject&worker=SapneshNaik'>Reject</a>)**

**Message:** Funder Sapnesh Naik


**3) <a href='https://sandbox.app.gitcommits.com/profile/PujaGovind'>PujaGovind</a> has applied to start work. (Funders only: <a href='https://sandbox.app.gitcommits.com/issue/funder-1-issue-1?action=approve&worker=PujaGovind'>Approve</a> | <a href='https://sandbox.app.gitcommits.com/issue/funder-1-issue-1?action=reject&worker=PujaGovind'>Reject</a>)**

**Message:** PujaGovind



<hr>

**This issue has a bounty of $50.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/funder-1-issue-1).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/help)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a> has been approved to start work.**

<hr />

**Message:** approved


<a href='https://sandbox.app.gitcommits.com/issue/funder-1-issue-1'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/Suman-Banakar'>Suman-Banakar</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://sandbox.app.gitcommits.com/issue/funder-1-issue-1'>Click Here to view more</a> on GitCommits Bounty detail page.
